<div id="ajax-example" data-bind="scope:'ajaxexample'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
    <script type="text/x-magento-init">
        {
        "#ajax-example": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "ajaxexample": {
                        "component": "AHT_Salesagents/js/commision-report"
                    }
                }
            }
        }
    }
    </script>
</div>

